# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/maksimshagaev/Boids-Praktika

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/maksimshagaev/Boids-Praktika

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maksimshagaev/Boids-Praktika/CMakeFiles /Users/maksimshagaev/Boids-Praktika//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maksimshagaev/Boids-Praktika/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Boids

# Build rule for target.
Boids: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boids
.PHONY : Boids

# fast build rule for target.
Boids/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/build
.PHONY : Boids/fast

car.o: car.cpp.o
.PHONY : car.o

# target to build an object file
car.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/car.cpp.o
.PHONY : car.cpp.o

car.i: car.cpp.i
.PHONY : car.i

# target to preprocess a source file
car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/car.cpp.i
.PHONY : car.cpp.i

car.s: car.cpp.s
.PHONY : car.s

# target to generate assembly for a file
car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/car.cpp.s
.PHONY : car.cpp.s

data.o: data.cpp.o
.PHONY : data.o

# target to build an object file
data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/data.cpp.o
.PHONY : data.cpp.o

data.i: data.cpp.i
.PHONY : data.i

# target to preprocess a source file
data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/data.cpp.i
.PHONY : data.cpp.i

data.s: data.cpp.s
.PHONY : data.s

# target to generate assembly for a file
data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/data.cpp.s
.PHONY : data.cpp.s

fieldb.o: fieldb.cpp.o
.PHONY : fieldb.o

# target to build an object file
fieldb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/fieldb.cpp.o
.PHONY : fieldb.cpp.o

fieldb.i: fieldb.cpp.i
.PHONY : fieldb.i

# target to preprocess a source file
fieldb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/fieldb.cpp.i
.PHONY : fieldb.cpp.i

fieldb.s: fieldb.cpp.s
.PHONY : fieldb.s

# target to generate assembly for a file
fieldb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/fieldb.cpp.s
.PHONY : fieldb.cpp.s

input.o: input.cpp.o
.PHONY : input.o

# target to build an object file
input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/input.cpp.o
.PHONY : input.cpp.o

input.i: input.cpp.i
.PHONY : input.i

# target to preprocess a source file
input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/input.cpp.i
.PHONY : input.cpp.i

input.s: input.cpp.s
.PHONY : input.s

# target to generate assembly for a file
input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/input.cpp.s
.PHONY : input.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/main.cpp.s
.PHONY : main.cpp.s

model.o: model.cpp.o
.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i
.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s
.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/model.cpp.s
.PHONY : model.cpp.s

output.o: output.cpp.o
.PHONY : output.o

# target to build an object file
output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/output.cpp.o
.PHONY : output.cpp.o

output.i: output.cpp.i
.PHONY : output.i

# target to preprocess a source file
output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/output.cpp.i
.PHONY : output.cpp.i

output.s: output.cpp.s
.PHONY : output.s

# target to generate assembly for a file
output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/output.cpp.s
.PHONY : output.cpp.s

pigeon.o: pigeon.cpp.o
.PHONY : pigeon.o

# target to build an object file
pigeon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/pigeon.cpp.o
.PHONY : pigeon.cpp.o

pigeon.i: pigeon.cpp.i
.PHONY : pigeon.i

# target to preprocess a source file
pigeon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/pigeon.cpp.i
.PHONY : pigeon.cpp.i

pigeon.s: pigeon.cpp.s
.PHONY : pigeon.s

# target to generate assembly for a file
pigeon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Boids.dir/build.make CMakeFiles/Boids.dir/pigeon.cpp.s
.PHONY : pigeon.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Boids"
	@echo "... car.o"
	@echo "... car.i"
	@echo "... car.s"
	@echo "... data.o"
	@echo "... data.i"
	@echo "... data.s"
	@echo "... fieldb.o"
	@echo "... fieldb.i"
	@echo "... fieldb.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... output.o"
	@echo "... output.i"
	@echo "... output.s"
	@echo "... pigeon.o"
	@echo "... pigeon.i"
	@echo "... pigeon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

